services:
  db:
    image: mysql
    environment:   
      MYSQL_ROOT_PASSWORD: 'eventapppass'
    ports:
      - "3306:3306"
  
  phpAdmin:
    image: phpmyadmin
    environment: 
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"